### ISSUE TITLE
[feat] chat over sockets

### ISSUE THREAD

**Issue by SOONG-E** [42-Jolly-pingpong/back-end#25]
## 📢 Description

소켓을 통한 채팅 기능을 구현합니다.

## 💎 Requirements

기존 HTTP통신 방식에서 소켓 통신 방식으로 변환합니다.

## ✨ Todo

- [ ] 클라이언트가 서버와 연결됐을 때 참여중인 모든 채팅방에 join해야합니다.
- [ ] 클라이언트가 새로운 메시지를 보냈을 때 채팅방 참가자들에게 같은 메시지를 전달해야합니다.
- [ ] 채팅방 정보에 변화가 생겼을 때 채팅방 참가자들에게 채팅방 정보를 업데이트해줘야합니다.
- [ ] 엔티티를 수정해 채팅방에 새로운 챗이 와있는 지 구분해야합니다.
