### ISSUE TITLE
[feat] 42Oauth-token

### ISSUE THREAD

**Issue by ebcode2021** [42-Jolly-pingpong/back-end#8]
## 📢 Description

웹사이트에서 로그인 하기 위해서는, 42OAuth를 통해 access-token을 발급 받아 이미 DB에 해당 유저가 존재하는지(기존 유저인지) 혹은 존재하지 않는지(신규 유저인지) 확인이 필요합니다.
42api를 활용해 access-token 발급을 받는 기능을 구현하고자 합니다.

## 💎 Requirements

- intra.42.fr에서 login 후 app 등록이 잘 되어 있어야 한다.
- DB에 해당 유저가 있는 경우, main page로 redirect 한다.
- DB에 해당 유저가 없는 경우, 42 authorize page로 redirect한 후, 승인을 받으면 sign-up page로 redirect 한다. 이 때, 승인을 받지 못하면, alert혹은 modal을 띄워 다시 welcome page로 redirect 된다.

** 42 autorize 이후, JWT 생성에 대한 기능은 다른 issue에서 작업예정

## ✨ Todo

- [x] 42 app 등록
- [x] auth module 생성
- [x] 유효한 access-token 반환받기
- [x] access token으로 user 정보가 불러오기
- [x] user 정보가 DB에 이미 있는지 확인하기
- [x] user 정보가 DB에 <b>있는</b>경우, main으로 redirect
- [x] user 정보가 DB에 <b>없는</b>경우, 42 authorize page로 redirect
- [x] 42 authorize page의 결과에 따른 페이징 처리 (yes -> sign-up page,  no -> welcome page)

## 🐣 ETC

- Blackhole에 빠진 유저의 경우, user정보를 42api에 GET 요청하는 상황에 return 결과는 어떤지 체크
